version: 2.1

partial:
  node-image: &node-image circleci/node:12.14.1

jobs:
  deps-install:
    docker:
      - image: *node-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-install-node12-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - yarn-install-node12-{{ checksum "package.json" }}
            - yarn-install-node12
          paths:
            - node_modules
            - ~/.cache/yarn
      - run:
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-install-node12-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  code-lint:
    docker:
      - image: *node-image
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn lint

  commit-lint:
    docker:
      - image: *node-image
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn lint:commit:ci

  publish:
    docker:
      - image: *node-image
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn release

workflows:
  version: 2
  build:
    jobs:
      - deps-install
      - code-lint:
          requires:
            - deps-install
      - commit-lint:
          requires:
            - deps-install
      - publish:
          filters:
            branches:
              only:
                - master
          requires:
            - code-lint
            - commit-lint
